name: frame_vision_api
description: "Captures an image from Brilliant Labs Frame and sends it to a user-specified API for processing"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5
  image: ^4.3.0
  logging: ^1.3.0
  share_plus: ^10.1.0
  shared_preferences: ^2.3.2
  simple_frame_app: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/simple_frame_app/lua/battery.min.lua
    - packages/simple_frame_app/lua/camera.min.lua
    - packages/simple_frame_app/lua/code.min.lua
    - packages/simple_frame_app/lua/data.min.lua
    - packages/simple_frame_app/lua/plain_text.min.lua
    - assets/frame_app.lua
